language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

cache: pip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran

install:
  - pip install -r requirements-travis.txt

script:
  - python setup.py build
  - python setup.py install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55cf16b611593edcb09d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
