site_name: AIMBAT
copyright: Copyright &copy; 2023 Simon Lloyd

# Repository
repo_name: pysmo/aimbat
repo_url: https://github.com/pysmo/aimbat

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    # - navigation.indexes
    # - navigation.sections
    # - navigation.tabs
    - navigation.top
  palette:
    # # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        # name: Switch to system preference

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji ""
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
        - ">>>"

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            - https://matplotlib.org/stable/objects.inv
  - termynal

nav:
  - Home: index.md
  - User Guide:
      - user-guide/overview.md
      - user-guide/installation.md
      - user-guide/data.md
      - user-guide/cli.md
      - user-guide/gui.md
  - help.md
  - Code Reference: reference/
  - Contributors: contributors.md
  - Changelog: changelog.md
